import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';

export interface ReportSection {
  heading: string;
  html: string;
}

export interface ReportInput {
  title: string;
  subtitle?: string;
  platform: 'meta' | 'google' | 'linkedin' | 'cross';
  skill: string;
  sections: ReportSection[];
  period?: { since: string; until: string };
  accountRef?: string;
}

function escape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function renderShell(input: ReportInput): string {
  const now = new Date().toISOString();
  const periodHtml = input.period
    ? `<span class="text-slate-400">${escape(input.period.since)} → ${escape(input.period.until)}</span>`
    : '';
  const accountHtml = input.accountRef
    ? `<span class="text-slate-400">account: <code class="text-emerald-300">${escape(input.accountRef)}</code></span>`
    : '';
  const sections = input.sections
    .map(
      (s) => `
      <section class="mt-10">
        <h2 class="text-xl font-semibold text-slate-100 border-b border-slate-800 pb-2">${escape(s.heading)}</h2>
        <div class="mt-4">${s.html}</div>
      </section>`,
    )
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>${escape(input.title)} — AdSkills</title>
<script src="https://cdn.tailwindcss.com"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
<style>
  body { background: radial-gradient(ellipse at top, #0f172a, #020617); min-height: 100vh; }
  .card { background: rgba(15, 23, 42, 0.6); border: 1px solid rgba(148, 163, 184, 0.1); backdrop-filter: blur(10px); }
  table { border-collapse: collapse; width: 100%; }
  th, td { padding: 0.6rem 0.9rem; text-align: left; border-bottom: 1px solid rgba(148,163,184,0.1); }
  th { font-weight: 600; color: #cbd5e1; text-transform: uppercase; font-size: 0.72rem; letter-spacing: 0.05em; }
  td { color: #e2e8f0; font-size: 0.92rem; }
  code { background: rgba(16,185,129,0.1); padding: 0.1rem 0.35rem; border-radius: 0.25rem; }
</style>
</head>
<body class="text-slate-100 font-sans">
  <div class="max-w-6xl mx-auto px-6 py-10">
    <header class="card rounded-2xl p-6">
      <div class="flex items-center justify-between">
        <div>
          <p class="text-emerald-400 text-xs uppercase tracking-widest font-semibold">AdSkills · ${escape(input.platform)} · ${escape(input.skill)}</p>
          <h1 class="text-3xl font-bold mt-2">${escape(input.title)}</h1>
          ${input.subtitle ? `<p class="text-slate-400 mt-1">${escape(input.subtitle)}</p>` : ''}
        </div>
        <div class="text-right text-xs space-y-1">
          <div>${escape(now)}</div>
          ${periodHtml}
          ${accountHtml ? `<div>${accountHtml}</div>` : ''}
        </div>
      </div>
    </header>
    <main class="mt-6 card rounded-2xl p-6">
      ${sections}
    </main>
    <footer class="mt-6 text-center text-xs text-slate-500">
      Generated by <a class="text-emerald-400" href="https://github.com/">adskills</a>
    </footer>
  </div>
</body>
</html>`;
}

export function renderCreativeTable(
  rows: Array<{
    name: string;
    file: string;
    sizeKb: number;
    imageHash?: string;
    creativeId?: string;
    adId?: string;
    status: 'ok' | 'failed';
    error?: string;
  }>,
): string {
  const body = rows
    .map((r) => {
      const badge =
        r.status === 'ok'
          ? `<span class="text-emerald-400">✓ ok</span>`
          : `<span class="text-rose-400">✗ ${escape(r.error ?? 'failed')}</span>`;
      return `<tr>
        <td>${escape(r.name)}</td>
        <td class="text-slate-400">${escape(r.file)}</td>
        <td>${r.sizeKb.toFixed(0)} KB</td>
        <td><code>${escape(r.imageHash ?? '—')}</code></td>
        <td><code>${escape(r.creativeId ?? '—')}</code></td>
        <td><code>${escape(r.adId ?? '—')}</code></td>
        <td>${badge}</td>
      </tr>`;
    })
    .join('\n');
  return `<div class="overflow-x-auto"><table>
    <thead><tr>
      <th>Name</th><th>File</th><th>Size</th><th>Image Hash</th><th>Creative ID</th><th>Ad ID</th><th>Status</th>
    </tr></thead>
    <tbody>${body}</tbody>
  </table></div>`;
}

export async function writeReport(input: ReportInput, rootDir: string): Promise<string> {
  const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 16);
  const path = resolve(rootDir, `${input.platform}-ads`, input.skill, `${ts}.html`);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, renderShell(input));
  return path;
}
